services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - "./:/var/${COMPOSE_PROJECT_NAME}"
    ports:
      - "${HOST_IP}:35080:80"
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  php:
    image: ${DOCKER_PHP_BUILT_IMAGE}
    pull_policy: ${PULL_POLICY:-never}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: '${USERID}:${GROUPID}'
    volumes:
      - ${DATA_PATH_STORE:-${DATA_PATH}}:/var/${COMPOSE_PROJECT_NAME}/${DATA_PATH}
      - ${OPTIONAL_VOLUME:-/dev/null:/dev/null}
    working_dir: ${WORKING_DIR:-/var/${COMPOSE_PROJECT_NAME}}
    networks:
      - ${COMPOSE_PROJECT_NAME}-network
    environment:
    - DATA_PATH=${DATA_PATH}

networks:
  chatbot-php-network:
    name: '${COMPOSE_PROJECT_NAME}-network'
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:1::/112
          gateway: fdff:1:1::1

